# Generated by Django 4.2.7 on 2023-12-02 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('numbOfTasks', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='rightAnswCount',
        ),
        migrations.AddField(
            model_name='answerquiz',
            name='correctAns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answerquiz',
            name='isSubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerquiz',
            name='taskID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.task'),
        ),
        migrations.AddField(
            model_name='answerquiz',
            name='textAns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerquiz',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='isSubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='rightAnsw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='toUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='uAnswer',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='answerquiz',
            name='uAnswer',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('mark', models.FloatField(blank=True, null=True)),
                ('sClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.vclass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workToDo', models.ManyToManyField(blank=True, related_name='student', to='quiz.work')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.work'),
        ),
    ]
