# Generated by Django 4.2.7 on 2023-12-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_vclass_work_remove_task_rightanswcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vclass',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vclass',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
