# Generated by Django 4.2.7 on 2023-12-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_vclass_gender_alter_vclass_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
