# Generated by Django 4.2.7 on 2023-11-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ariphm', '0006_tasklist_quiz_answerquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='taskId',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='task',
            name='variants',
        ),
    ]
