# Generated by Django 4.2.7 on 2023-11-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ariphm', '0007_remove_quiz_date_remove_quiz_taskid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerquiz',
            name='task',
        ),
        migrations.RemoveField(
            model_name='answerquiz',
            name='user',
        ),
    ]
